volumes:
  n8n_storage_krXXX:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/n8n_storage
  postgres_storage_krXXX:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres_storage
  qdrant_storage_krXXX:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/qdrant_storage

networks:
  demo:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo_krXXX']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - N8N_HOST=n8n-krXXX.ict-bz.ch
    - DOMAIN_NAME=ict-bz.ch
    - SUBDOMAIN=n8n-krXXX
    - N8N_SMTP_PORT=25
    - N8N_SMTP_SENDER="ICT-BZ <it@ict-bz.ch>"
    - N8N_SMTP_SSL=false
    - N8N_SMTP_STARTTLS=false
  env_file:
    - path: .env
      required: true

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres_krXXX
    networks: ['demo_krXXX']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage_krXXX:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *service-n8n
    hostname: n8n_krXXX
    container_name: n8n_krXXX
    restart: unless-stopped
    ports:
      - 567XXX:5678
    volumes:
      - n8n_storage_XXX:/home/node/.n8n
      - ./shared_krXXX:/data/shared
    depends_on:
      postgres:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: ['demo_krXXX']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage_krXXX:/qdrant/storage
